const mongoose = require('mongoose');

const DashboardWidgetSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    // The id generated by the frontend (e.g. wdg_1234)
    frontendId: {
        type: String,
        required: true
    },
    type: {
        type: String,
        required: true,
        enum: ['kpi', 'chart', 'table']
    },
    subtype: {
        type: String
    },
    title: {
        type: String,
        required: true
    },
    description: {
        type: String
    },
    width: {
        type: Number,
        default: 4
    },
    height: {
        type: Number,
        default: 4
    },
    settings: {
        type: mongoose.Schema.Types.Mixed, // Flexible object depending on widget type
        default: {}
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('DashboardWidget', DashboardWidgetSchema);
